# Generated by Django 6.0 on 2026-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_shippingaddressformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddressformmodel',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
