# Generated by Django 6.0 on 2026-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_shippingaddressformmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddressformmodel',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
