# Generated by Django 6.0 on 2026-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_shippingaddressformmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddressformmodel',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddressformmodel',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddressformmodel',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
