# Generated by Django 6.0 on 2026-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_size',
            field=models.CharField(choices=[('large', 'Large'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/brands/'),
        ),
    ]
