# Generated by Django 6.0 on 2026-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_theme',
            field=models.CharField(blank=True, choices=[('bg-black-darker', 'Black Darker'), ('bg-blue', 'Blue'), ('bg-silver', 'Silver'), ('bg-black', 'Black')], max_length=50, null=True),
        ),
    ]
